name: Build

on:
  workflow_call:

jobs:
  prepare:
    runs-on: ubuntu-latest-16-cores
    if: github.repository_owner == 'armadaproject'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Echo
        run: exit 0

  pack-nuget:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Echo
        run: exit 0