name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  checks: write
  actions: read
  security-events: write

jobs:
  lint:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    uses: ./.github/workflows/lint.yml
  test:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    uses: ./.github/workflows/test.yml
  build:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    uses: ./.github/workflows/build.yml
  # Virtual job that can be configured as a required check before a PR can be merged.
  all-required-checks-done:
    name: All required checks done
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    needs:
      - lint
      - test
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Echo context
        run: ${{ toJson(github) }}

      - uses: actions/github-script@v6
        with:
          script: |
            const results = ${{ toJSON(needs.*.result) }};
            if (results.every(res => res === 'success')) {
              core.info('All required checks succeeded');
            } else {
              core.setFailed('Some required checks failed');
            }

