name: "Lint"

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  ts-lint:
    name: Lint TypeScript
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: yarn
          cache-dependency-path: ./internal/lookout/ui/yarn.lock

  go-lint:
    name: Lint Go
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up Go (no caching)
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false