name: Tests

on:
  workflow_call:

permissions:
  contents: read
  checks: write

jobs:
  ts-unit-tests:
    name: TypeScript Unit Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Echo
        run: exit 0

  go-unit-tests:
    name: Golang Unit Tests
    needs: go-mod-up-to-date
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Echo
        run: exit 1

  go-integration-tests:
    name: Golang Integration Tests
    needs: go-mod-up-to-date
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Echo
        run: exit 0

  go-mod-up-to-date:
    name: Golang Mod Up To Date
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Echo
        run: exit 0

  proto-up-to-date:
    name: Proto Up To Date
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Echo
        run: exit 0
